services:
  api:
    build: 
      context: ./backend
    container_name: carole_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app

  web:
    build:
      context: ./frontend
    container_name: carole_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
